library app_routes;
import 'package:flutter/material.dart';
import '../../presentation/auth/forgot_password/ view/forgot_password_screen.dart';
import '../../presentation/auth/login/view/login_screen.dart';
import '../../presentation/auth/otp/view/create_new_password_screen.dart';
import '../../presentation/auth/otp/view/otp_verification_screen.dart';
import '../../presentation/auth/registration/view/registration_screen.dart';
import '../../presentation/home/view/home_screen.dart';
import '../../presentation/match_details/view/match_details_screen.dart';
import '../../presentation/voting/view/voting_screen.dart';
import '../../presentation/voting_rights/view/assign_voting_view.dart';
import 'route_name.dart';
part "route_config.dart";